# Generated by Django 5.2.8 on 2025-11-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='title',
        ),
    ]
