# Generated by Django 5.2.8 on 2025-11-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_carouselimage_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': 'Fotot e para'},
        ),
    ]
